'use client'

import { FormEvent, useState } from 'react'
import { Activity, ArrowRight, AudioLines, BarChart3, BrainCircuit, Check, ChevronDown, ChevronLeft, ChevronRight, CirclePlay, Cpu, Layers3, LockKeyhole, Menu, MessageSquareText, Radio, Sparkles, Twitch, X, Youtube, Zap } from 'lucide-react'

const navItems = [{ label: 'Product', href: '#how' }, { label: 'Features', href: '#features' }, { label: 'Pricing', href: '#pricing' }, { label: 'Integrations', href: '#integrations' }]
const testimonials = [
  { quote: 'DeckFlow cut my setup time from 45 minutes to 11. It is a game changer for anyone serious about streaming.', name: 'Maya Chen', role: 'Twitch Affiliate, 38K followers', initials: 'MC' },
  { quote: 'The AI is eerily accurate. After one week, it knew my production flow better than I did. It is like having a coproducer who never sleeps.', name: 'James Rodriguez', role: 'YouTube Live Producer, MediaStream Studios', initials: 'JR' },
  { quote: 'Consistency improved, errors dropped 78%, and everyone had more creative headspace. Worth every penny.', name: 'Patricia Okonkwo', role: 'Director of Production, SportsCast Africa', initials: 'PO' },
]
const faqs = [
  ['How quickly can I get set up?', 'Most creators connect their first deck and map core actions in under 15 minutes. DeckFlow imports supported OBS scenes to speed up configuration.'],
  ['Which hardware works with DeckFlow?', 'DeckFlow works with MIDI compatible controllers and popular stream deck hardware. You can also use the browser based virtual deck.'],
  ['How does the AI learn my production style?', 'It observes action sequences, audio patterns, scene timing, and recurring chat events. You stay in control and approve suggested automations before they run.'],
  ['Which platforms can I connect?', 'Connect Twitch, YouTube, Facebook, TikTok, OBS, Streamlabs, and major audio tools. Pro supports synchronized output across multiple destinations.'],
  ['Is my production data private?', 'Your workspace is encrypted in transit and at rest. Your private production patterns are never used to train models for another customer.'],
  ['Can I cancel whenever I want?', 'Yes. There is no annual commitment on monthly plans, and you can export your automation rules before you leave.'],
]

function track(event: string, detail?: string) { if (typeof window !== 'undefined') window.dispatchEvent(new CustomEvent('deckflow:analytics', { detail: { event, detail } })) }

function TrialForm() {
  const [email, setEmail] = useState('')
  const [status, setStatus] = useState<'idle' | 'loading' | 'success' | 'error'>('idle')
  async function submit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault(); setStatus('loading'); track('trial_conversion', 'footer_form')
    try {
      const res = await fetch(`${process.env.NEXT_PUBLIC_CONSTRUCTOR_API}/v1/forms/${process.env.NEXT_PUBLIC_PROJECT_ID}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email, interest: 'DeckFlow 14 day free trial' }) })
      if (!res.ok) throw new Error('Request failed')
      setStatus('success')
    } catch { setStatus('error') }
  }
  if (status === 'success') return <p className="rounded-xl border border-emerald-400/30 bg-emerald-400/10 px-5 py-4 text-emerald-200">✓ Message sent. We will contact you soon.</p>
  return <form onSubmit={submit} className="mx-auto flex max-w-xl flex-col gap-3 sm:flex-row">
    <label className="sr-only" htmlFor="trial-email">Work email</label>
    <input id="trial-email" type="email" required value={email} onChange={e => setEmail(e.target.value)} placeholder="you@studio.com" className="min-w-0 flex-1 rounded-xl border border-white/15 bg-[#0a0e27]/80 px-5 py-4 text-white outline-none placeholder:text-[#8b96ad] focus:border-[#3b82f6]" />
    <button disabled={status === 'loading'} className="rounded-xl bg-white px-6 py-4 font-bold text-[#0a0e27] transition hover:bg-blue-100 disabled:opacity-60">{status === 'loading' ? 'Sending…' : 'Start free trial'}</button>
    {status === 'error' && <p className="text-sm text-red-200 sm:absolute sm:mt-20">We could not send your request. Please try again.</p>}
  </form>
}

function DeckVisual() {
  const keys = [<Radio key="r" />, <AudioLines key="a" />, <MessageSquareText key="m" />, <Youtube key="y" />, <Twitch key="t" />, <Layers3 key="l" />, <Zap key="z" />, <BarChart3 key="b" />]
  return <div className="relative mx-auto h-[420px] w-full max-w-[660px] lg:h-[590px]" aria-label="DeckFlow intelligent stream control interface">
    <div className="absolute inset-[8%] rounded-full bg-blue-600/20 blur-[90px]"/><div className="orbit absolute left-[6%] top-[15%] h-[68%] w-[86%] rounded-[50%] border border-blue-400/20"/>
    {[['12%','20%'],['82%','17%'],['94%','55%'],['17%','78%']].map(([left,top],i)=><span key={i} style={{left,top}} className="pulse absolute h-2 w-2 rounded-full bg-cyan-300 shadow-[0_0_20px_#60a5fa]"/>)}
    <div className="absolute left-[8%] right-[4%] top-[17%] rounded-2xl border border-white/10 bg-[#11182e]/85 p-3 shadow-[0_40px_100px_rgba(0,102,255,.25)] backdrop-blur-xl sm:p-5 lg:top-[20%] lg:rotate-[-3deg]">
      <div className="mb-4 flex items-center justify-between border-b border-white/10 pb-3 text-xs text-[#8b96ad]"><span className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-emerald-400"/> LIVE CONTROL 04</span><span>01:24:18</span></div>
      <div className="grid grid-cols-[1fr_5rem] gap-3 sm:grid-cols-[1fr_7rem]"><div className="grid grid-cols-4 gap-2 sm:gap-3">{keys.map((icon,i)=><div key={i} className={`deckkey aspect-square rounded-lg border p-2 sm:p-3 ${i===0?'border-blue-400 bg-blue-500/25 text-blue-200':'border-white/10 bg-white/[.045] text-[#8b96ad]'}`}>{icon}</div>)}</div><div className="rounded-xl border border-blue-400/20 bg-blue-500/5 p-2"><div className="mb-2 text-[9px] text-blue-300">AI CONFIDENCE</div><div className="text-2xl font-bold">96%</div><div className="mt-3 space-y-1">{[78,94,61,87].map((width,i)=><div key={i} className="h-1 rounded bg-white/10"><div style={{width:`${width}%`}} className="h-full rounded bg-blue-500"/></div>)}</div></div></div>
    </div><div className="float absolute bottom-[5%] right-[2%] w-52 rounded-xl border border-cyan-300/20 bg-[#11182e]/90 p-4 shadow-2xl backdrop-blur-xl"><div className="flex items-center gap-2 text-xs text-cyan-300"><BrainCircuit size={15}/> NEXT ACTION</div><p className="mt-2 text-sm font-semibold">Switch to guest closeup</p><div className="mt-3 h-1 rounded bg-white/10"><div className="h-full w-[92%] rounded bg-cyan-400"/></div></div>
  </div>
}

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false), [testimonial, setTestimonial] = useState(0), [openFaq, setOpenFaq] = useState(0)
  return <main className="min-h-screen overflow-hidden bg-[#0a0e27] text-[#f7faff]">
    <nav className="fixed inset-x-0 top-0 z-50 border-b border-white/10 bg-[#0a0e27]/80 backdrop-blur-xl"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 lg:px-8">
      <a href="#top" className="flex items-center gap-3 font-heading text-xl font-bold"><span className="grid h-9 w-9 place-items-center rounded-lg bg-blue-600 shadow-[0_0_24px_rgba(0,102,255,.55)]"><Cpu size={19}/></span>Deck<span className="text-blue-400">Flow</span></a>
      <div className="hidden items-center gap-8 md:flex">{navItems.map(item=><a key={item.label} href={item.href} className="text-sm text-[#aab3c7] transition hover:text-white">{item.label}</a>)}</div>
      <a href="#trial" onClick={()=>track('cta_click','nav')} className="hidden rounded-lg bg-blue-600 px-5 py-3 text-sm font-bold shadow-[0_0_24px_rgba(0,102,255,.3)] transition hover:bg-blue-500 md:block">Start free trial</a>
      <button onClick={()=>setMenuOpen(!menuOpen)} aria-label="Toggle navigation" aria-expanded={menuOpen} className="rounded-lg border border-white/10 p-2 md:hidden">{menuOpen?<X/>:<Menu/>}</button>
    </div><div className={`absolute inset-x-0 top-20 border-b border-white/10 bg-[#0a0e27]/95 px-5 pb-6 backdrop-blur-xl transition-all duration-500 ease-[cubic-bezier(0.16,1,0.3,1)] md:hidden ${menuOpen?'translate-y-0 opacity-100 pointer-events-auto':'-translate-y-4 opacity-0 pointer-events-none'}`}>{navItems.map((item,i)=><a key={item.label} href={item.href} onClick={()=>setMenuOpen(false)} style={{transitionDelay:menuOpen?`${i*60}ms`:'0ms'}} className="block border-b border-white/10 py-4 text-lg transition-all">{item.label}</a>)}<a href="#trial" onClick={()=>setMenuOpen(false)} className="mt-5 block rounded-lg bg-blue-600 px-5 py-3 text-center font-bold">Start free trial</a></div></nav>

    <section id="top" className="relative min-h-[800px] pt-28 lg:min-h-screen"><div className="grid-glow absolute inset-0"/><div className="relative mx-auto grid max-w-7xl items-center gap-8 px-5 py-16 lg:grid-cols-[45%_55%] lg:px-8 lg:py-24"><div><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-blue-400/25 bg-blue-400/10 px-3 py-2 text-xs font-bold uppercase tracking-[.18em] text-blue-300"><Sparkles size={14}/> Production intelligence, live</div><h1 className="font-heading text-5xl font-bold leading-[.98] tracking-[-.045em] sm:text-6xl lg:text-[4.6rem]">Control every stream. <span className="text-gradient">Let AI handle the rest.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-[#aab3c7]">DeckFlow learns your production style and automates 80% of technical decisions, so you can create instead of manage.</p><div className="mt-9 flex flex-col gap-4 sm:flex-row sm:items-center"><a href="#trial" onClick={()=>track('cta_click','hero')} className="group flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-6 py-4 font-bold shadow-[0_0_35px_rgba(0,102,255,.35)] transition hover:bg-blue-500">Start your 14 day free trial <ArrowRight className="transition group-hover:translate-x-1" size={18}/></a><a href="#demo" onClick={()=>track('demo_play','hero')} className="flex items-center justify-center gap-2 px-3 py-3 font-semibold text-blue-300 underline decoration-blue-500/50 underline-offset-4"><CirclePlay size={20}/> Watch 2 minute demo</a></div><p className="mt-5 flex items-center gap-2 text-xs text-[#8b96ad]"><Check size={14} className="text-emerald-400"/> No credit card required <span className="text-white/20">•</span> Cancel anytime</p></div><DeckVisual/></div></section>

    <section className="relative z-10 border-y border-white/10 bg-[#11162b]/80"><div className="mx-auto grid max-w-7xl grid-cols-2 px-5 py-8 lg:grid-cols-[1fr_1.25fr_1fr_1fr_1.3fr] lg:px-8">{[['47,000+','Active creators'],['2.3M','Scenes automated monthly'],['4×','Faster setup time'],['99.94%','Platform uptime']].map((stat,i)=><div key={stat[1]} className="border-white/10 px-3 py-4 lg:border-r lg:px-6"><strong className={`font-heading text-2xl sm:text-3xl ${i%2?'text-blue-300':''}`}>{stat[0]}</strong><p className="mt-1 text-xs text-[#8b96ad]">{stat[1]}</p></div>)}<div className="col-span-2 flex items-center gap-3 px-3 pt-5 text-xs text-[#8b96ad] lg:col-span-1 lg:px-6 lg:pt-0"><LockKeyhole size={18} className="text-blue-300"/> Trusted by Streamlabs, Elgato, and OBS partners</div></div></section>

    <section id="how" className="mx-auto max-w-7xl px-5 py-28 lg:px-8"><div className="mb-14 max-w-2xl"><p className="eyebrow">From input to instinct</p><h2>Three steps to smarter streaming</h2><p className="section-copy">Go from a blank deck to an intelligent production partner without rebuilding your current workflow.</p></div><div className="relative grid gap-4 md:grid-cols-3"><div className="flowline absolute left-[16%] right-[16%] top-9 hidden h-px bg-gradient-to-r from-blue-600 via-cyan-300 to-blue-600 md:block"/>{[[Cpu,'Connect your hardware','Link any MIDI compatible stream deck or build a custom one. DeckFlow syncs instantly.'],[BrainCircuit,'Teach the AI your style','Record 3 to 5 streams. AI observes button sequences, audio patterns, and chat interactions.'],[Zap,'Autopilot your production','Predict next actions automatically. Switch scenes, mix audio, and respond to chat hands free.']].map(([Icon,title,copy],i)=><article key={String(title)} className="relative rounded-2xl border border-white/10 bg-[#11162b] p-7"><div className="relative z-10 mb-8 grid h-14 w-14 place-items-center rounded-xl border border-blue-400/30 bg-blue-600/15 text-blue-300"><Icon size={25}/><span className="absolute -right-2 -top-2 rounded-full bg-blue-600 px-2 py-0.5 text-[10px] font-bold">0{i+1}</span></div><h3>{title}</h3><p className="mt-3 text-sm leading-6 text-[#8b96ad]">{copy}</p></article>)}</div></section>

    <section id="features" className="bg-[#070a1b] px-5 py-28 lg:px-8"><div className="mx-auto max-w-7xl"><div className="mx-auto mb-14 max-w-2xl text-center"><p className="eyebrow">Command center</p><h2>Intelligence in every control</h2><p className="section-copy">Five production engines share context in real time, giving every scene, signal, and message the right response.</p></div><div className="grid gap-4 md:grid-cols-6 md:grid-rows-2">
      <article className="bento md:col-span-4"><div><span className="iconbox"><Layers3/></span><h3>Smart scene prediction</h3><p>Next scene suggestions adapt to your rundown, speaker activity, and past decisions.</p></div><div className="mt-8 rounded-xl border border-white/10 bg-black/20 p-4"><div className="mb-4 flex items-center justify-between text-xs text-[#8b96ad]"><span>NEXT SCENE</span><span className="text-emerald-300">AI READY</span></div>{['Guest closeup','Screen share','Wide studio'].map((item,i)=><div key={item} className={`mb-2 flex items-center justify-between rounded-lg border p-3 text-sm ${i===0?'border-blue-400/40 bg-blue-500/10':'border-white/5 bg-white/[.02]'}`}><span>{item}</span><span className="text-xs text-[#8b96ad]">{[96,73,41][i]}%</span></div>)}</div></article>
      <article id="demo" className="bento md:col-span-2"><span className="iconbox"><AudioLines/></span><h3>Real time audio intelligence</h3><p>Balance every source before clipping reaches your audience.</p><div className="mt-10 flex h-24 items-center gap-1">{[30,62,45,88,55,72,38,94,62,48,80,40].map((height,i)=><span key={i} style={{height:`${height}%`}} className="flex-1 rounded-full bg-gradient-to-t from-blue-700 to-cyan-300"/>)}</div></article>
      <article className="bento md:col-span-2"><span className="iconbox"><MessageSquareText/></span><h3>Chat to action automation</h3><p>Turn recurring messages into useful, moderated actions.</p><div className="mt-7 rounded-lg bg-black/20 p-3 text-xs"><span className="text-blue-300">IF</span> chat contains “schedule”<br/><span className="text-emerald-300">THEN</span> post next stream card</div></article>
      <article id="integrations" className="bento md:col-span-2"><span className="iconbox"><Radio/></span><h3>Multi stream sync</h3><p>Keep every destination aligned from one live timeline.</p><div className="mt-8 flex gap-3"><span className="platform"><Twitch/></span><span className="platform"><Youtube/></span><span className="platform"><Radio/></span></div></article>
      <article className="bento md:col-span-2"><span className="iconbox"><BarChart3/></span><h3>Production analytics</h3><p>See attention, action, and reliability in one clear view.</p><div className="mt-7 flex h-20 items-end gap-2">{[35,58,46,79,62,91,84].map((height,i)=><span key={i} style={{height:`${height}%`}} className="flex-1 rounded-t bg-blue-500/60"/>)}</div></article>
    </div></div></section>

    <section className="mx-auto max-w-7xl px-5 py-28 lg:px-8"><div className="grid items-center gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">Creator signal</p><h2>Built for the moment live begins</h2><div className="mt-8 flex gap-3"><button aria-label="Previous testimonial" onClick={()=>setTestimonial((testimonial+2)%3)} className="rounded-full border border-white/15 p-3 hover:bg-white/5"><ChevronLeft/></button><button aria-label="Next testimonial" onClick={()=>setTestimonial((testimonial+1)%3)} className="rounded-full border border-white/15 p-3 hover:bg-white/5"><ChevronRight/></button></div></div><div className="relative rounded-3xl border border-blue-400/20 bg-gradient-to-br from-blue-600/15 to-white/[.03] p-8 sm:p-12"><div className="mb-8 text-5xl leading-none text-blue-400">“</div><blockquote className="font-heading text-2xl leading-relaxed sm:text-3xl">{testimonials[testimonial].quote}</blockquote><div className="mt-9 flex items-center gap-4"><span className="grid h-12 w-12 place-items-center rounded-full bg-blue-600 font-bold">{testimonials[testimonial].initials}</span><div><strong>{testimonials[testimonial].name}</strong><p className="text-sm text-[#8b96ad]">{testimonials[testimonial].role}</p></div></div><div className="absolute bottom-6 right-8 flex gap-2">{testimonials.map((_,i)=><button key={i} aria-label={`Show testimonial ${i+1}`} onClick={()=>setTestimonial(i)} className={`h-1.5 rounded-full transition-all ${i===testimonial?'w-8 bg-blue-400':'w-2 bg-white/20'}`}/>)}</div></div></div></section>

    <section id="pricing" className="border-y border-white/10 bg-[#11162b] px-5 py-28 lg:px-8"><div className="mx-auto max-w-7xl"><div className="mx-auto mb-14 max-w-2xl text-center"><p className="eyebrow">Simple pricing</p><h2>Scale your production, not your workload</h2><p className="section-copy">Try every plan free for 14 days. Change or cancel whenever your workflow changes.</p></div><div className="grid items-stretch gap-4 lg:grid-cols-3">{[
      ['Creator','$29','For focused solo creators',['Up to 8 custom stream decks','50 automation rules','Basic AI suggestions','Twitch and YouTube chat','Community support']],
      ['Pro','$79','For serious multichannel shows',['Unlimited stream decks','500 automation rules','Advanced predictive learning','All major streaming platforms','Priority support']],
      ['Enterprise','Custom','For broadcast teams',['Shared production workspaces','Unlimited automation rules','Advanced permissions','Dedicated onboarding','Priority production support']],
    ].map((plan,i)=><article key={plan[0] as string} className={`relative flex flex-col rounded-2xl border p-7 ${i===1?'border-blue-400 bg-blue-600/10 shadow-[0_0_50px_rgba(0,102,255,.14)] lg:-my-4 lg:py-11':'border-white/10 bg-[#0a0e27]/60'}`}>{i===1&&<span className="absolute right-5 top-0 -translate-y-1/2 rounded-full bg-blue-500 px-3 py-1 text-xs font-bold uppercase tracking-wider">Most popular</span>}<h3>{plan[0]}</h3><p className="mt-2 text-sm text-[#8b96ad]">{plan[2]}</p><div className="my-7"><strong className="font-heading text-4xl">{plan[1]}</strong>{plan[1]!=='Custom'&&<span className="text-[#8b96ad]"> / month</span>}</div><ul className="mb-8 flex-1 space-y-3">{(plan[3] as string[]).map(item=><li key={item} className="flex gap-3 text-sm text-[#c5ccda]"><Check size={17} className="shrink-0 text-blue-400"/>{item}</li>)}</ul><a href="#trial" onClick={()=>track('pricing_interaction',plan[0] as string)} className={`rounded-xl px-5 py-3 text-center font-bold transition ${i===1?'bg-blue-600 hover:bg-blue-500':'border border-white/15 hover:bg-white/5'}`}>{i===2?'Talk to sales':'Start free trial'}</a></article>)}</div></div></section>

    <section className="mx-auto grid max-w-7xl gap-12 px-5 py-28 lg:grid-cols-[.7fr_1.3fr] lg:px-8"><div><p className="eyebrow">Questions, answered</p><h2>Ready before you go live</h2><p className="section-copy">Everything you need to know before connecting your first control.</p></div><div>{faqs.map(([question,answer],i)=><article key={question} className="border-b border-white/10"><button onClick={()=>setOpenFaq(openFaq===i?-1:i)} aria-expanded={openFaq===i} className="flex w-full items-center justify-between gap-5 py-6 text-left font-heading text-lg font-semibold"><span>{question}</span><ChevronDown className={`shrink-0 transition ${openFaq===i?'rotate-180 text-blue-400':''}`}/></button><div className={`grid transition-all duration-300 ${openFaq===i?'grid-rows-[1fr] pb-6':'grid-rows-[0fr]'}`}><p className="overflow-hidden leading-7 text-[#8b96ad]">{answer}</p></div></article>)}</div></section>

    <section id="trial" className="relative px-5 py-24 lg:px-8"><div className="cta-grid relative mx-auto max-w-7xl overflow-hidden rounded-3xl border border-blue-300/20 bg-blue-600 px-6 py-20 text-center shadow-[0_0_90px_rgba(0,102,255,.2)] sm:px-12"><div className="relative z-10"><p className="mb-4 text-sm font-bold uppercase tracking-[.2em] text-blue-100">Your next stream starts here</p><h2 className="mx-auto max-w-3xl text-white">Put your production on intelligent autopilot</h2><p className="mx-auto mb-9 mt-5 max-w-xl text-blue-100">Join creators building calmer, sharper, more consistent live shows. Your 14 day trial takes minutes to set up.</p><TrialForm/></div></div></section>

    <footer className="border-t border-white/10 px-5 py-12 lg:px-8"><div className="mx-auto grid max-w-7xl gap-10 md:grid-cols-[1.5fr_1fr_1fr_1fr]"><div><a href="#top" className="flex items-center gap-3 font-heading text-xl font-bold"><span className="grid h-9 w-9 place-items-center rounded-lg bg-blue-600"><Cpu size={19}/></span>DeckFlow</a><p className="mt-4 max-w-xs text-sm leading-6 text-[#8b96ad]">AI powered control for creators who want every live moment to feel intentional.</p></div>{[['Product',['#how','How it works','#features','Features','#integrations','Integrations']],['Company',['#trial','Contact','#pricing','Pricing','#top','Product']],['Resources',['#demo','Demo','#pricing','Plans','#trial','Start trial']]].map(([title,links])=><div key={title as string}><strong className="text-sm">{title}</strong><div className="mt-4 space-y-3">{Array.from({length:3},(_,i)=><a key={(links as string[])[i*2+1]} href={(links as string[])[i*2]} className="block text-sm text-[#8b96ad] hover:text-white">{(links as string[])[i*2+1]}</a>)}</div></div>)}</div><div className="mx-auto mt-12 flex max-w-7xl flex-col justify-between gap-4 border-t border-white/10 pt-7 text-xs text-[#69758e] sm:flex-row"><p>© 2026 DeckFlow. All rights reserved.</p><p>Built for creators, producers, and broadcast teams.</p></div></footer>
  </main>
}
